image: oracle/graalvm-ce:20.0.0-java8

services:
  - docker:latest
  - docker:dind
  - gradle

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - ./gradlew buildNative --docker-build=true

production:
  stage: deploy
  script:
    - heroku container:login
    - docker build -f src/main/docker/Dockerfile.native -t quarkus/$HEROKU_APP .
    - docker pull registry.heroku.com/$HEROKU_APP/web || true
    - heroku container:push web --app=$HEROKU_APP --context-path .
    - heroku container:release web -a $HEROKU_APP