sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    # GraalVM
    - env: JDK='GraalVM 19'
      install: . ./install-jdk.sh --url "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java8-linux-amd64-19.3.1.tar.gz"

script:
  - ./gradlew buildNative

notifications:
  email:
    on_success: never
    on_failure: always