micronaut:
  server:
    cors:
      enabled: true
  application:
    name: api
  caches:
    addon-cache:
      expire-after-write: "60m"
---
engvid:
  url: "https://www.engvid.com"
---
datasources:
  default:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
---
flyway:
  datasources:
    default:
      locations: classpath:migrations
