micronaut:
  server:
    cors:
      enabled: true
  application:
    name: api
  caches:
    addon-cache:
      expire-after-write: "24h"
---
engvid:
  url: "https://www.engvid.com"
---
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
---
flyway:
  datasources:
    default:
      locations: classpath:migrations
