micronaut:
  server:
    cors:
      enabled: true
  application:
    name: api
  caches:
    all-video:
      expire-after-write: "60m"
    search-video:
      expire-after-write: "60m"
    addon-cache:
      expire-after-write: "60m"
---
engvid:
  url: "https://www.engvid.com"
---
datasources:
  default:
    url: "${DATABASE_JDBC_URL:url}"
    username: "${DATABASE_USER:user}"
    password: "${DATABASE_PASSWORD:password}"
    driverClassName: org.postgresql.Driver
---
flyway:
  datasources:
    default:
      locations: classpath:migrations
